Gemfile
Gemfile.lock
config/initializers/high_voltage.rb
lib/generators/static/USAGE
lib/generators/static/static_generator.rb
lib/generators/static/templates/static_page.html

Facilitates adding static pages
Issue #5

Feature/5 Create static page generator

---

app/assets/stylesheets/tul_ohist.css.scss
app/controllers/catalog_controller.rb
app/views/advanced/_facet_layout.html.erb

Hide advanced search sort button
Add digital collection to advanced search
Remove toggle attributes
Modify facet partial non-collapsible

Integrate digital collections into form

---

Gemfile
Gemfile.lock
app/helpers/tul_ohist_helper.rb
app/views/layouts/application.html.erb
app/views/layouts/blacklight.html.erb
config/environments/production.rb

* Ticket has been sent to Chris Doyle to create an account and send tracking code.

add google analytics code to the site for tracking.

---

app/assets/stylesheets/tul_ohist.css.scss
app/views/catalog/_home_text.html.erb
config/locales/tul_ohist.en.yml

Ref: #2 
- Add full department name
- Remove border
- Recrop Tallit image
- Reorganize SCSS

Feature/2 Fix landing page title and images

---

lib/cdm_utils.rb

Update the validation of foxml files during ingest

---

config/collections.yml.example

Populate example file with real data

---

app/helpers/tul_ohist_helper.rb

Use transcript filename for PDF filename

---

app/views/pages/feinstein_collection.html.erb
app/views/pages/walter_massey_phillips_oral_histories.html.erb

Add root URL to browse-by links

---

app/controllers/catalog_controller.rb

Removes duplicate collection search params

---

app/views/pages/feinstein_collection.html.erb
app/views/pages/walter_massey_phillips_oral_histories.html.erb

Updated image caption to link whole text

---

app/views/catalog/_home_text.html.erb
config/collections.yml.example

Ref #77 
To apply change, execute: `cp config/collections.yml.example config/collections.yml`

Updated text to "Feinstein Center"

---

app/views/catalog/_facets.html.erb

Restore "Browse All" button located above facets

---

app/views/pages/feinstein_collection.html.erb
app/views/pages/walter_massey_phillips_oral_histories.html.erb

Add collection facet to browse-by link in collection home pages

---

app/views/catalog/_document_list.html.erb
spec/factories/transcripts.rb
spec/features/results_numberings_spec.rb

Add starting value to order list on each page

---

app/views/catalog/_home_text.html.erb

Clearing float adds space above "about" section

---

app/views/catalog/_facets.html.erb
app/views/catalog/_search_form.html.erb
config/locales/tul_ohist.en.yml

Ref: #109 
- Move button to search form
- Localize "Browse All" text

Move 'Browse All' button to header bar

---

app/views/pages/walter_massey_phillips_oral_histories.html.erb

Break caption before "September"

---

app/assets/stylesheets/tul_ohist.css.scss
app/views/_ada_note.html.erb
app/views/catalog/_home_text.html.erb
app/views/pages/feinstein_collection.html.erb
app/views/pages/walter_massey_phillips_oral_histories.html.erb
config/locales/tul_ohist.en.yml

Ref #13 
- Add ADA note to localization yml file
- Add mail_to helper to note
- Add DIV tag to ADA note

Add ADA Note to Landign Page

---

config/collections.yml

Ref #105 
Maps "Great Migration" to "Migration from the African Diaspora" collection

Add "Great Migration" collection to search pull down

---

app/assets/stylesheets/tul_ohist.css.scss
app/helpers/tul_ohist_helper.rb
app/models/transcript.rb
app/views/catalog/_show_transcript.html.erb
app/views/layouts/blacklight.html.erb
config/ensemble.yml
lib/tasks/cdm_to_foxml_oralhistory.xsl
lib/tul_ohist/datastreams/digital_datastream.rb
spec/factories/transcripts.rb
spec/helpers/audio_player_helper_spec.rb
spec/lib/tul_ohist/datastreams/digital_datastream_spec.rb
spec/samples/digital_datastream.xml

136 handle multi part recordings rebase

---

app/views/shared/_footer.html.erb
config/locales/tul_ohist.en.yml

#104 
- In preparation for finalized footer content

Put footer text in localized config

---

app/controllers/catalog_controller.rb

Move type facet to top and change title

---

app/assets/stylesheets/tul_ohist.css.scss
app/views/catalog/_home_text.html.erb
app/views/pages/african_american_migration_oral_histories.html
config/collections.yml
config/routes.rb

Ref #103 
All parts are in place for the African American Migration to Philadelphia.
@bibliotechy: If it looks good, can we merge so QA can have a look at the home page thumbnail, links, and landing page.
@gabrielgalson: We need final text, image caption, finding aid and related collections text and link to complete issue #103.

103 New landing page

---

config/application.rb

Precompile fonts for production

---

app/helpers/tul_ohist_helper.rb
config/locales/tul_ohist.en.yml

Change "track" to "part" for multi-part audio

---

app/helpers/tul_ohist_helper.rb
app/views/catalog/_show_transcript.html.erb
config/collections.yml

@bibliotechy : refactore?
https://github.com/tulibraries/tul_ohist/blob/3df5b4c5be32c190bdf3ddf068f13fe6c480126e/app/helpers/tul_ohist_helper.rb#L15-L16
https://github.com/tulibraries/tul_ohist/blob/3df5b4c5be32c190bdf3ddf068f13fe6c480126e/app/helpers/tul_ohist_helper.rb#L15-L16

Customize contacts with collections config

---

app/helpers/tul_ohist_helper.rb
app/views/catalog/_show_transcript.html.erb
config/collections.yml
config/locales/tul_ohist.en.yml

40 update contact in context box

---

config/locales/blacklight.en.yml

Addresses support issue #INC000001163089

Remove SCRC form application name
